project:
  type: website
  resources:
    - "*.cljs"
    - "*.svg"
    - "*.png"
    - "*.tif"

website:
  title: "Civitas个人小站"
  favicon: "favicon.ico"
  site-url: "https://clojurecivitas.github.io"
  image: "/images/civitas-icon.svg"
  draft-mode: visible
  open-graph: true
  navbar:
    logo: "/images/civitas-icon.svg"
    logo-alt: "Clojure Civitas Logo"
    right:
      - about.qmd
      - posts.qmd
      - drafts.qmd
      - icon: github
        href: "https://github.com/ClojureCivitas/clojurecivitas.github.io"
      - icon: rss
        href: posts.xml

format:
  html:
    theme:
      light: [ flatly, brand, styles.scss, styles-light.scss ]
      dark: [ darkly, brand, styles.scss, styles-dark.scss ]
    respect-user-color-scheme: true
    lightbox: true

brand:
  light: brand-light.yml
  dark: brand-dark.yml
